language: go
sudo: false

os:
  - linux

go:
  - 1.13

script:
  # Windows 386 build
  - GOOS=windows GOARCH=386 VERSION=${TRAVIS_TAG} make release
  # Windows amd64 build
  - GOOS=windows GOARCH=amd64 VERSION=${TRAVIS_TAG} make release
  # Linux 386 build
  - GOOS=linux GOARCH=386 VERSION=${TRAVIS_TAG} make release
  # Linux amd64 build
  - GOOS=linux GOARCH=amd64 VERSION=${TRAVIS_TAG} make release
  # Darwin amd64 build
  - GOOS=darwin GOARCH=amd64 VERSION=${TRAVIS_TAG} make release

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
    - release/underblog-*.zip
    - release/underblog-*.tar.gz
  on:
    tags: true
  file_glob: true
  skip_cleanup: true
